model_dir_path: /models
chatbot_dir_path: /workspace
server_boot_file_name: server_boot_config.yaml

embedding_model: sentence-transformers/all-MiniLM-L6-v2
LLM_model: "cjvt/GaMS-1B"

top_k_chunks: 50
reorder_top_n_chunks: 10

llm_temperature: 0.7
llm_top_p: 0.9
llm_top_k_sampling: 50
llm_repetition_penalty: 1.1
llm_do_sample: true
llm_max_new_tokens: 256

nn_device: cuda